### ISSUE TITLE
Avoid using ids in your html

### ISSUE THREAD

**Issue by shiryz** [WebAhead6/checkdone#11]
> IDs shouldn't be used in selectors because these rules are too tightly coupled with the HTML and have no possibility of reuse. It's much preferred to use classes in selectors and then apply a class to an element in the page.

From the [following link](http://csslint.net/about.html#:~:text=ids%20Don't%20use%20IDs,an%20element%20in%20the%20page.)

**Comment by Tarekb93** [comment]
done.
